ALTER TABLE profiles ADD COLUMN favorite INTEGER NOT NULL DEFAULT 0;
ALTER TABLE profiles ADD COLUMN notes TEXT;
ALTER TABLE profiles ADD COLUMN last_played TEXT;
ALTER TABLE profiles ADD COLUMN launch_count INTEGER NOT NULL DEFAULT 0;
ALTER TABLE profiles ADD COLUMN mod_count INTEGER NOT NULL DEFAULT 0;
ALTER TABLE profiles ADD COLUMN disk_usage INTEGER NOT NULL DEFAULT 0;
ALTER TABLE profiles ADD COLUMN ram_mb INTEGER;
ALTER TABLE profiles ADD COLUMN instance_group TEXT;
