UPDATE profiles
SET loader = 'forge'
WHERE loader = 'fabric'
  AND (
    loader_version LIKE '47.%'
    OR loader_version LIKE '48.%'
    OR loader_version LIKE '49.%'
    OR loader_version LIKE '50.%'
    OR loader_version LIKE '40.%'
    OR loader_version LIKE '41.%'
    OR loader_version LIKE '42.%'
    OR loader_version LIKE '43.%'
    OR loader_version LIKE '36.%'
    OR loader_version LIKE '37.%'
    OR loader_version LIKE '38.%'
    OR loader_version LIKE '39.%'
    OR loader_version LIKE '31.%'
    OR loader_version LIKE '14.%'
    OR loader_version LIKE '10.%'
    OR loader_version LIKE '9.%'
    OR loader_version LIKE '7.%'
    OR name LIKE '%[FORGE]%'
    OR name LIKE '%(FORGE)%'
    OR name LIKE '%Forge%'
  );
