CREATE TABLE IF NOT EXISTS servers (
	id TEXT PRIMARY KEY,
	name TEXT NOT NULL,
	host TEXT NOT NULL,
	port INTEGER NOT NULL DEFAULT 25565,
	favorite BOOLEAN NOT NULL DEFAULT 0,
	created_at TEXT NOT NULL
);
