ALTER TABLE profiles ADD COLUMN use_gamemode INTEGER NOT NULL DEFAULT 0;
ALTER TABLE profiles ADD COLUMN use_mangohud INTEGER NOT NULL DEFAULT 0;
ALTER TABLE profiles ADD COLUMN force_dedicated_gpu INTEGER NOT NULL DEFAULT 0;
ALTER TABLE profiles ADD COLUMN use_gamescope INTEGER NOT NULL DEFAULT 0;
ALTER TABLE profiles ADD COLUMN gamescope_width INTEGER;
ALTER TABLE profiles ADD COLUMN gamescope_height INTEGER;
ALTER TABLE profiles ADD COLUMN gamescope_fsr INTEGER NOT NULL DEFAULT 0;
ALTER TABLE profiles ADD COLUMN force_full_verification INTEGER NOT NULL DEFAULT 0;
