const { chromium } = require('playwright-core');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const { setupLauncherDemo } = require('../scripts/launcher-video-fixture.cjs');
(async () => {
 const browser = await chromium.launch({headless:true,executablePath:process.env.LUXMC_CHROMIUM_EXECUTABLE});
 const page = await browser.newPage({viewport:{width:1600,height:1100}});
 const errors=[]; page.on('pageerror',error=>errors.push(String(error)));
 await setupLauncherDemo(page);
 await page.addInitScript(() => {
  const canvas=document.createElement('canvas');canvas.width=64;canvas.height=32;const painter=canvas.getContext('2d');painter.fillStyle='rgb(180,40,60)';painter.fillRect(0,0,64,32);const cape=canvas.toDataURL('image/png');
  canvas.height=64;painter.fillStyle='rgb(40,160,100)';painter.fillRect(0,0,64,64);const skin=canvas.toDataURL('image/png');
  const invoke=window.electronAPI.invoke;
  const wrapped=async(command,args)=>{
   if(command==='plugin:dialog|open')return location.pathname==='/skins'?'C:/demo/Cape.png':'C:/Downloads/My Wallpaper.mp4';
   if(command==='auth_read_local_texture')return cape;
   if(command==='namemc_import_skin')return {skinId:'63455d7069b397c2',skinUrl:skin};
   if(command==='wallpaper_import')return 'C:/Luxmc/wallpapers/managed.mp4';
   if(command==='wallpaper_prepare_poster')throw Error('FFmpeg unavailable');
   if(command==='media_server_port')return null;
   return invoke(command,args);
  };
  window.electronAPI.invoke=wrapped;window.__TAURI_INTERNALS__.invoke=wrapped;
  window.__TAURI_INTERNALS__.convertFileSrc=value=>value.includes('wallpapers/managed')?'/qa-wallpaper.mp4':value;
 });
 await page.route('**/qa-wallpaper.mp4',route=>route.fulfill({contentType:'video/mp4',body:fs.readFileSync('tests/fixtures/wallpaper.mp4')}));
 await page.goto('http://127.0.0.1:1420/');await page.locator('main').waitFor();
 const sort=page.getByRole('button',{name:'Ordenar instâncias',exact:true});
 const triggers=page.locator('.glass-select-trigger');assert.equal(await triggers.count(),2);
 for(const trigger of await triggers.all())assert.equal(await trigger.locator('svg').count(),2);
 await triggers.first().click();await page.getByRole('option',{name:'Nome',exact:true}).click();assert.equal(await triggers.first().getAttribute('aria-expanded'),'false');
 await page.goto('http://127.0.0.1:1420/instances');await page.getByRole('heading',{name:/Suas instâncias/}).waitFor();await page.screenshot({path:'docs/validation/followup-instance-stats.png'});
 await page.goto('http://127.0.0.1:1420/skins');await page.getByRole('button',{name:'Aplicar skin e capa',exact:true}).waitFor();
 await page.getByRole('button',{name:'Explorar NameMC',exact:true}).click();
 await page.waitForFunction(()=>window.launcherDemo.calls.some(call=>call.command==='namemc_open_picker'));
 assert.equal(await page.getByRole('dialog',{name:'Escolha sua próxima skin'}).count(),0);
 await page.evaluate(()=>window.launcherDemo.selectNameMc());await page.getByText('NameMC 63455d7069b397c2',{exact:true}).waitFor();
 const saved=()=>page.evaluate(()=>JSON.parse(localStorage.getItem('luxmc_saved_skins')));
 await page.getByRole('button',{name:'Importar capa PNG',exact:true}).click();
 await page.waitForFunction(()=>JSON.parse(localStorage.getItem('luxmc_saved_skins')).some(s=>s.name.startsWith('NameMC')&&s.capeType==='custom'));
 const assigned=(await saved()).find(s=>s.name.startsWith('NameMC'));assert.ok(assigned.capeUrl.startsWith('data:image/png;base64,'));
 await page.locator('[role="button"]').filter({hasText:'Steve • Demonstração'}).first().click();
 await page.waitForFunction(()=>JSON.parse(sessionStorage.getItem('luxmc_skin_draft:luxmc:00000000-0000-4000-8000-000000000001')||'null')?.cape==='none');
 await page.getByText('NameMC 63455d7069b397c2',{exact:true}).click();await page.waitForTimeout(500);
 assert.equal((await saved()).find(s=>s.name.startsWith('NameMC')).capeUrl,assigned.capeUrl);
 await page.reload();await page.getByRole('button',{name:'Aplicar skin e capa',exact:true}).waitFor();assert.ok(await page.getByRole('button',{name:'Aplicar skin e capa',exact:true}).isEnabled());
 assert.equal((await saved()).find(s=>s.name.startsWith('NameMC')).capeUrl,assigned.capeUrl);
 await page.goto('http://127.0.0.1:1420/settings');await page.getByRole('tab',{name:/Aparência/}).click();
 await page.getByTitle('Importe qualquer vídeo MP4/WebM ou imagem PNG/JPG/GIF/WebP').click();
 await page.waitForFunction(()=>JSON.parse(localStorage.getItem('luxmc_wallpaper_library')).some(w=>w.url==='C:/Luxmc/wallpapers/managed.mp4'));
 const preview=page.locator('video[src="/qa-wallpaper.mp4"]').first();await preview.waitFor();await page.waitForFunction(()=>Array.from(document.querySelectorAll('video')).some(video=>video.videoWidth>0&&video.currentTime>0));
 const library=await page.evaluate(()=>JSON.parse(localStorage.getItem('luxmc_wallpaper_library')));assert.equal(library[0].name,'My Wallpaper');
 await page.screenshot({path:'docs/validation/followup-wallpaper-preview.png'});
 assert.deepEqual(errors,[]);console.log('PASS: single filter surfaces, direct NameMC catalog and selection, cape paired per skin through switching/reload, managed wallpaper path/name, video preview without FFmpeg, zero page errors.');await browser.close();
})().catch(error=>{console.error(error);process.exit(1);});
