const {chromium}=require(process.env.LUXMC_PLAYWRIGHT_MODULE || 'playwright');
const assert=require('node:assert/strict');
(async()=>{
 const browser=await chromium.launch({headless:true});
 const page=await browser.newPage({viewport:{width:1440,height:1000},reducedMotion:'reduce'});
 const errors=[];page.on('pageerror',e=>errors.push(String(e)));
 await page.addInitScript(()=>{
   const profile={id:'fabric-profile',name:'Fabric de teste',icon:'grass_block',mcVersion:'1.20.1',loader:'fabric',loaderVersion:'0.16.0',gameDir:'/tmp/luxmc-test',createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),ramMb:4096,modCount:2};
   const account={id:'offline_test',uuid:'offline_test',username:'Steve',accessToken:'',skinUrl:'https://mineskin.eu/skin/Steve'};
   const events={};const queue=['luxmc://install/modpack?id=fabulously-optimized&source=modrinth'];window.testCalls=[];
   const invoke=async(command,args)=>{
     window.testCalls.push({command,args});
     if(command==='app_init')return {account,profiles:[profile],activeProfileId:profile.id,devMode:true};
     if(command==='deep_links_take')return queue.splice(0);
     if(command==='mods_project_details')return {id:args.projectId,slug:args.projectId,title:args.projectId==='sodium'?'Sodium':'Fabulously Optimized',description:'Projeto de teste',body:'',bodyType:'markdown',iconUrl:null,downloads:1000000,categories:['fabric'],loaders:['fabric'],gameVersions:['1.20.1'],source:args.source,gallery:[]};
     if(command==='curseforge_status')return true;
     if(command==='profiles_list'||command==='instances_list')return [profile];
     if(command==='mods_versions')return [{id:'v1',name:'v1',versionNumber:'1',files:[{filename:'pack.mrpack',url:'https://cdn.modrinth.com/pack.mrpack',size:1,sha1:''}]}];
     if(command==='mods_download_to_temp')return '/tmp/pack.mrpack';
     if(command==='instance_import_mrpack')return {...profile,id:'new-profile',name:'Fabulously Optimized'};
     if(command==='plugin:store|load')return 1;
     if(command==='plugin:store|get')return [{animations:false,liveWallpaper:false,soundscapesEnabled:false,soundEnabled:false},true];
     if(command==='plugin:event|listen')return 1;
     if(command==='mods_search'||command==='java_scan'||command==='screenshots_list'||command==='skins_list')return [];
     if(command==='get_system_specs')return {totalRamMb:16384,osDistro:'Linux',arch:'x86_64'};
     if(command==='minecraft_uuid')return null;
     if(command==='social_request')return {me:{id:'me',username:'Steve'},friends:[{id:'friend-id',username:'Alex',status:'in_game',incoming:false,lastSeen:null,activity:'Fabric de teste',mcVersion:'1.20.1',loader:'fabric',serverIp:'friend.example.org',serverPort:25567}]};
     return null;
   };
   window.electronAPI={invoke,on:(event,callback)=>{(events[event]??=[]).push(callback);return ()=>events[event]=events[event].filter(v=>v!==callback)}};
   window.__TAURI_INTERNALS__={invoke,transformCallback:()=>1,convertFileSrc:()=>'/grass_head.png'};
   window.testEvent=(event,payload)=>{for(const callback of events[event]||[])callback(payload)};
   window.testLink=url=>{queue.push(url);for(const callback of events['deep-link-pending']||[])callback(null)};
 });
 await page.goto('http://127.0.0.1:1420/');
 await page.getByRole('dialog',{name:'Instalar modpack'}).waitFor({timeout:30000});
 assert.match(page.url(),/\/mods/);
 assert.equal(await page.locator('#modpack-inst-name').inputValue(),'Fabulously Optimized');
 await page.waitForTimeout(600);
 await page.screenshot({path:'docs/visual/2026-09-19/launcher-modpack.png'});
 await page.getByRole('button',{name:'Cancelar',exact:true}).click();
 await page.evaluate(()=>window.testLink('luxmc://install/mod?id=sodium&source=modrinth'));
 await page.getByRole('dialog',{name:'Escolha a instância'}).waitFor();
 assert.ok(await page.getByRole('dialog').getByText('Fabric de teste').count());
 await page.waitForTimeout(600);
 await page.screenshot({path:'docs/visual/2026-09-19/launcher-mod.png'});
 await page.getByRole('button',{name:'Fechar seleção de instância'}).click();
 await page.evaluate(()=>window.testLink('luxmc://skin/apply?url=https%3A%2F%2Fmineskin.eu%2Fskin%2FAlex&model=slim'));
 await page.waitForURL('**/skins');
 await page.waitForTimeout(1000);
 await page.waitForTimeout(600);
 await page.screenshot({path:'docs/visual/2026-09-19/launcher-skin.png'});
 assert.ok(await page.getByText('Skin recebida do portal.',{exact:false}).count());
 await page.getByRole('button',{name:'Aplicar',exact:true}).click();
 await page.waitForFunction(()=>window.testCalls.some(call=>call.command==='auth_change_skin'));
 const skin=await page.evaluate(()=>window.testCalls.find(call=>call.command==='auth_change_skin'));
 assert.equal(skin.args.variant,'slim');assert.equal(skin.args.skinUrl,'https://mineskin.eu/skin/Alex');
 await page.evaluate(()=>window.testLink('luxmc://join/server?ip=play.example.org&port=25566'));
 await page.waitForFunction(()=>window.testCalls.some(call=>call.command==='launch_game'));
 const launch=await page.evaluate(()=>window.testCalls.find(call=>call.command==='launch_game'));
 assert.equal(launch.args.request.serverIp,'play.example.org');
 assert.equal(launch.args.request.serverPort,25566);
 await page.evaluate(()=>{window.testEvent('game-exit',{success:true,code:0});window.testLink('luxmc://join/friend?code=friend-id')});
 await page.waitForFunction(()=>window.testCalls.filter(call=>call.command==='launch_game').length===2);
 const friendJoin=await page.evaluate(()=>window.testCalls.filter(call=>call.command==='launch_game')[1]);
 assert.equal(friendJoin.args.request.serverIp,'friend.example.org');assert.equal(friendJoin.args.request.serverPort,25567);
 console.log(JSON.stringify({launcher:'passed',errors}));
 await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
