(async () => {
    const checks = [];
    window.masterProgress = checks;
    const wait = async (predicate, label, timeout = 12000) => {
        const end = performance.now() + timeout;
        while (!predicate()) {
            if (performance.now() > end) throw new Error(`Timeout: ${label}`);
            await new Promise(resolve => setTimeout(resolve, 80));
        }
    };
    const assert = (condition, label) => { if (!condition) throw new Error(label); checks.push(label); };
    const click = (selector, text) => {
        const element = [...document.querySelectorAll(selector)].find(item => item.textContent.includes(text));
        if (!element) throw new Error(`Controle ausente: ${text}`);
        element.click();
    };
    try {
        const { goto } = await import('/node_modules/@sveltejs/kit/src/runtime/app/navigation.js');
        const textures = await import('/src/lib/utils/textureImage.ts');
        const { getFullCapeDataUrl } = await import('/src/lib/utils/capeTextures.ts');
        await goto('/skins');
        await wait(() => document.querySelector('[aria-label="Visualizador 3D de Skin"]'), 'skins');
        assert(!JSON.parse(localStorage.getItem('luxmc_saved_skins')).some(item => item.id === 'default_steve'), 'Padrões removidos das salvas');
        await wait(() => performance.getEntriesByType('resource').some(entry => /skinview3d.*\.js/.test(entry.name)), 'biblioteca 3D');
        const libraryUrl = performance.getEntriesByType('resource').find(entry => /skinview3d.*\.js/.test(entry.name)).name;
        const { SkinViewer } = await import(libraryUrl);
        const originalLoad = SkinViewer.prototype.loadSkin;
        const viewers = new Map();
        SkinViewer.prototype.loadSkin = function (...args) {
            viewers.set(this.canvas, this);
            return originalLoad.apply(this, args);
        };
        const before = JSON.parse(localStorage.getItem('luxmc_saved_skins')).length;
        window.uploadTexture = getFullCapeDataUrl('cherry');
        window.uploadPath = '/tmp/cape Pink Cherry Blossom.png';
        click('button', 'Adicionar skin');
        await wait(() => document.body.textContent.includes('Capa identificada'), 'importação de capa');
        assert(JSON.parse(localStorage.getItem('luxmc_saved_skins')).length === before, 'Capa não entra nas skins salvas');
        const signal = new AbortController().signal;
        const avatar = await textures.createSkinAvatar(window.uploadTexture, signal);
        const standard = await textures.createSkinAvatar('/steve.png', signal);
        assert(avatar === standard, 'Avatar rejeita UV de capa e usa rosto válido');
        window.uploadTexture = window.testSkinData;
        window.uploadPath = '/tmp/Minha textura.png';
        click('button', 'Adicionar skin');
        await wait(() => JSON.parse(localStorage.getItem('luxmc_saved_skins')).length === before + 1, 'importação de skin');
        await wait(() => [...document.querySelectorAll('button')].some(b => b.textContent.trim() === 'Aplicar skin e capa' && !b.disabled), 'aplicar');
        assert(!window.testCalls.some(call => call.command === 'auth_save_appearance'), 'Seleção permanece rascunho');
        const canvas = document.querySelector('[aria-label="Visualizador 3D de Skin"] canvas');
        await wait(() => viewers.has(canvas), 'renderização da skin importada');
        const viewer = viewers.get(canvas);
        const advances = async label => {
            const start = viewer.playerWrapper.rotation.y;
            await new Promise(resolve => setTimeout(resolve, 400));
            const change = viewer.playerWrapper.rotation.y - start;
            assert(change > 0.03 && change < 0.4, label);
        };
        await advances('Skin importada com capa mantém rotação contínua');
        const capture = canvas.setPointerCapture.bind(canvas);
        const release = canvas.releasePointerCapture.bind(canvas);
        canvas.releasePointerCapture = () => {};
        canvas.setPointerCapture = () => {};
        const pointer = (type, extras = {}) => canvas.dispatchEvent(new PointerEvent(type, { pointerId: 7, pointerType: 'mouse', button: 0, buttons: 1, clientX: 100, clientY: 100, bubbles: true, ...extras }));
        pointer('pointerdown');
        let angle = viewer.playerWrapper.rotation.y;
        pointer('pointermove', { clientX: 180 });
        assert(viewer.playerWrapper.rotation.y - angle > 0.9, 'Arraste gira a skin após importação');
        pointer('lostpointercapture');
        await advances('Perda da captura libera rotação automática');
        pointer('pointerdown');
        window.dispatchEvent(new Event('blur'));
        await advances('Perda de foco libera o arraste');
        pointer('pointerdown');
        pointer('pointermove', { buttons: 0 });
        await advances('Mouse solto fora do canvas não prende rotação');
        pointer('pointerdown');
        pointer('pointercancel');
        await advances('Cancelamento do ponteiro retoma rotação');
        const graphics = viewer.renderer.getContext();
        const loseContext = graphics.getExtension('WEBGL_lose_context');
        assert(!!loseContext, 'Perda de contexto disponível para teste');
        loseContext.loseContext();
        await wait(() => document.body.textContent.includes('Reiniciar prévia 3D'), 'fallback após perda de contexto');
        assert(canvas.classList.contains('invisible'), 'Canvas perdido oculto; seleção preservada na prévia alternativa');
        loseContext.restoreContext();
        await wait(() => !canvas.classList.contains('invisible'), 'recuperação do contexto');
        await advances('Rotação retomada após restaurar WebGL');
        canvas.setPointerCapture = capture;
        canvas.releasePointerCapture = release;


        await goto('/settings');
        await goto('/skins');
        await wait(() => document.querySelector('[aria-label="Visualizador 3D de Skin"] canvas'), 'retorno ao personalizador');
        assert([...document.querySelectorAll('button')].some(b => b.textContent.trim() === 'Aplicar skin e capa' && !b.disabled), 'Rascunho não aplicado preservado ao sair e voltar');
        for (let cycle = 0; cycle < 8; cycle++) {
            click('[role="button"]', 'Minha textura');
            await new Promise(resolve => setTimeout(resolve, 80));
            const currentCanvas = document.querySelector('[aria-label="Visualizador 3D de Skin"] canvas');
            await wait(() => viewers.has(currentCanvas) && !currentCanvas.classList.contains('invisible'), 'skin selecionada no ciclo ' + cycle);
            const current = viewers.get(currentCanvas);
            current.playerWrapper.rotation.y = 0;
            current.renderer.setRenderTarget(null);
            current.renderer.render(current.scene, current.camera);
            const gl = current.renderer.getContext();
            const pixels = new Uint8Array(gl.drawingBufferWidth * gl.drawingBufferHeight * 4);
            gl.readPixels(0, 0, gl.drawingBufferWidth, gl.drawingBufferHeight, gl.RGBA, gl.UNSIGNED_BYTE, pixels);
            let visiblePixels = 0;
            let coloredPixels = 0;
            for (let i = 3; i < pixels.length; i += 4) if (pixels[i] > 0) { visiblePixels++; if (Math.max(pixels[i-1], pixels[i-2], pixels[i-3]) > 15) coloredPixels++; }
            assert(coloredPixels > 100, "Textura tem detalhes coloridos de frente no ciclo " + cycle);
            assert(visiblePixels > 500 && visiblePixels < pixels.length / 4 * .8 && gl.getError() === gl.NO_ERROR, 'Modelo renderizado sem quadro preto no ciclo ' + cycle);
            await goto('/settings');
            await goto('/skins');
        }
        SkinViewer.prototype.loadSkin = originalLoad;

        click('button', 'Aplicar skin e capa');
        await wait(() => window.testCalls.some(call => call.command === 'auth_save_appearance'), 'salvamento explícito');
        const appearance = window.testCalls.find(call => call.command === 'auth_save_appearance').args;
        const applied = textures.textureCanvas(await textures.loadTextureImage(appearance.skinUrl, signal));
        assert(textures.classifyTexture(applied) === 'skin', 'Aplicação envia skin corporal válida');
        click('button', 'Editar skin');
        await wait(() => [...document.querySelectorAll('button')].some(b => b.textContent.includes('Fino (Alex)')), 'modal de modelo');
        click('button', 'Fino (Alex)');
        assert(JSON.parse(localStorage.getItem('luxmc_saved_skins')).find(item => item.name === 'Minha textura').model === 'alex', 'Modelo fino persistido na skin salva');
        window.testCalls.length = 0;
        await goto('/instances/fabric-profile');
        await wait(() => window.testCalls.some(call => call.command === 'instance_file_tree'), 'dados essenciais');
        await new Promise(resolve => setTimeout(resolve, 500));
        const scans = window.testCalls.filter(call => ['instance_file_tree','instance_worlds_list','instances_screenshots','java_scan'].includes(call.command));
        assert(scans.length === 1 && scans[0].args.subPath === 'mods', 'Entrada da instância consulta apenas mods');
        click('button', 'Shaders');
        await wait(() => window.testCalls.some(call => call.command === 'instance_file_tree' && call.args.subPath === 'shaderpacks'), 'shaders sob demanda');
        assert(true, 'Shaders carregados ao selecionar aba');
        click('[role="tab"]', 'Mundos');
        await wait(() => window.testCalls.some(call => call.command === 'instance_worlds_list'), 'mundos sob demanda');
        click('[role="tab"]', 'Screenshots');
        await wait(() => window.testCalls.some(call => call.command === 'instances_screenshots'), 'screenshots sob demanda');
        assert(true, 'Mundos e screenshots carregados sob demanda');
        await goto('/mods');
        await wait(() => document.body.textContent.includes('Pack 35'), 'catálogo completo');
        assert(!document.querySelector('[data-virtual-list]'), 'Catálogo usa a rolagem principal sem viewport aninhado');
        let viewport;
        const { gameLogs } = await import('/src/lib/stores/app.svelte.ts');
        gameLogs.clear();
        for (let index = 0; index < 500; index++) gameLogs.add('stdout', `Linha ${index}: ${'mensagem longa '.repeat(index % 5 + 1)}`);
        await goto('/logs');
        await wait(() => document.querySelector('[data-virtual-list] [data-index]'), 'logs virtuais');
        viewport = document.querySelector('[data-virtual-list]');
        viewport.scrollTop = viewport.scrollHeight;
        await wait(() => viewport.textContent.includes('Linha 499:'), 'último log');
        assert(viewport.querySelectorAll('[data-index]').length <= 20, '500 logs com até 20 linhas montadas');
        const { newsState } = await import('/src/lib/stores/news.svelte.ts');
        await newsState.load(true);
        await goto('/news');
        await wait(() => document.body.textContent.includes('Minecraft Live Recap'), 'notícias reais');
        assert(!newsState.offline, 'Notícias oficiais recebidas pelo comando nativo simulado');
        window.failNews = true;
        await newsState.load(true);
        assert(newsState.offline && newsState.items.length > 0, 'Falha de rede preserva notícias e informa modo offline');
        window.failNews = false;
        const { themeStore } = await import('/src/lib/stores/theme.svelte.ts');
        themeStore.setCustomWallpaper('/tmp/wallpaper.png', 'image');
        assert(localStorage.getItem('luxmc_custom_wallpaper') === '/tmp/wallpaper.png', 'Caminho original do wallpaper preservado');
        themeStore.setBackground('obsidian', false);
        themeStore.init();
        assert(themeStore.background === 'obsidian' && !document.documentElement.classList.contains('has-custom-wallpaper'), 'Reabertura respeita fundo escolhido');
        await goto('/settings');
        await wait(() => document.querySelector('#rendering-title'), 'controles gráficos');
        const quality = [...document.querySelectorAll('select')].find(el => el.textContent.includes('960 px'));
        quality.value = '960'; quality.dispatchEvent(new Event('change', { bubbles: true }));
        await new Promise(resolve => setTimeout(resolve, 300));
        await goto('/skins');
        await goto('/settings');
        await wait(() => document.querySelector('#rendering-title'), 'retorno às configurações');
        const reopenedQuality = [...document.querySelectorAll('select')].find(el => el.textContent.includes('960 px'));
        assert(reopenedQuality.value === '960', 'Qualidade gráfica preservada ao reabrir a página');
        await goto('/instances/fabric-profile');
        await wait(() => document.querySelector('[aria-label="Configurações da instância"]'), 'configurações da instância');
        document.querySelector('[aria-label="Configurações da instância"]').click();
        await wait(() => document.querySelector('[role="dialog"][aria-label="Configurações da instância"]'), 'modal');
        const modal = document.querySelector('[role="dialog"][aria-label="Configurações da instância"]');
        assert(modal.querySelector('header img') && modal.querySelector('input[type="url"]'), 'Modal mantém banner editável e arte do perfil');
        document.querySelector('[aria-label="Fechar configurações"]').click();
        window.masterResult = { passed: true, checks };
    } catch (error) { window.masterResult = { passed: false, checks, error: String(error), stack: error.stack, errors: window.browserErrors, body: document.body.innerText.slice(-4500), virtual: [...document.querySelectorAll("[data-virtual-list]")].map(e=>({height:e.clientHeight,scroll:e.scrollHeight,html:e.innerHTML.slice(0,500)})) }; }
})();
