const { chromium } = require(process.env.LUXMC_PLAYWRIGHT_MODULE || 'playwright');
const assert = require('node:assert/strict');
const fs = require('node:fs');
(async () => {
 const browser = await chromium.launch({headless:true});
 const page = await browser.newPage({viewport:{width:1440,height:1000},reducedMotion:'reduce'});
 const errors=[];page.on('pageerror',e=>errors.push(String(e)));
 await page.route('**/api/latest-release',r=>r.fulfill({json:{tag_name:'v1.7.4',assets:[{name:'Luxmc-x86_64.AppImage',size:104857600,browser_download_url:'https://github.com/predabr/luxmc/releases/download/v1.7.4/Luxmc.AppImage'}]}}));
 await page.route('**/api/account/me',r=>r.fulfill({status:401,json:{}}));
 await page.route('https://api.modrinth.com/**',r=>r.fulfill({json:{hits:[{project_id:'AANobbMI',slug:'sodium',title:'Sodium',description:'Otimização gráfica para Minecraft',author:'CaffeineMC',downloads:1000000,categories:['fabric'],icon_url:'assets/logo.png'}]}}));
 await page.goto('http://127.0.0.1:8765/');
 await page.locator('[data-luxmc]').first().waitFor();
 assert.match(await page.locator('[data-luxmc]').first().getAttribute('href'),/^luxmc:\/\/install\/mod\?id=AANobbMI/);
 await page.evaluate(()=>showLauncherFallback());
 await page.locator('#launcherFallback[open]').waitFor();
 assert.equal(await page.locator('#launcherFallbackDownload').getAttribute('href'),'/download/linux');
 fs.mkdirSync('docs/visual/2026-09-19',{recursive:true});
 await page.screenshot({path:'docs/visual/2026-09-19/portal-fallback.png'});
 await page.keyboard.press('Escape');
 assert.equal(await page.locator('#launcherFallback').evaluate(e=>e.open),false);
 await page.setViewportSize({width:390,height:844});
 await page.evaluate(()=>showLauncherFallback());
 assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 await page.screenshot({path:'docs/visual/2026-09-19/portal-mobile.png'});
 await page.goto('http://127.0.0.1:8765/skins.html?nick=Alex&model=slim');
 await page.waitForTimeout(1000);
 assert.equal(await page.locator('#playerNickInput').inputValue(),'Alex');
 assert.equal(await page.locator('input[name="skinModel"]:checked').inputValue(),'slim');
 const link=await page.evaluate(()=>{let value;window.openLuxmc=url=>value=url;saveToLauncher();return value});
 const parsed=new URL(link);assert.equal(parsed.hostname,'skin');assert.equal(parsed.searchParams.get('model'),'slim');assert.match(parsed.searchParams.get('url'),/Alex/);
 console.log(JSON.stringify({website:'passed',errors}));
 await browser.close();
})().catch(error=>{console.error(error);process.exit(1)});
